#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 14 15:33:48 2019

@author: aditya
"""

# -*- coding: utf-8 -*-
"""mnist_keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWXQ9e2zJQ-91HPm86RqWU-ytCnDuYvp
"""

# import module
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.utils import plot_model

#Load data set
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

#Building model
model = tf.keras.models.Sequential([
   tf.keras.layers.Flatten(input_shape=(28,28)),
   tf.keras.layers.Dense(100, activation='sigmoid'),
   tf.keras.layers.Dropout(.2),
   tf.keras.layers.Dense(10, activation='softmax')
   ])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

#Training model
history = model.fit(x_train, y_train, validation_split=0.33, 
                    epochs=5, batch_size=10, verbose=1)
model.evaluate(x_test, y_test)